"""Bundle the local PDF font and AI-SECRETT logo for reliable browser exports."""

import base64
from pathlib import Path


assets = Path(__file__).resolve().parents[1] / "assets"
font = base64.b64encode((assets / "NotoSans-Regular.ttf").read_bytes()).decode("ascii")
logo = base64.b64encode((assets / "ai-secrett-logo.png").read_bytes()).decode("ascii")
(assets / "pdf-assets.js").write_text(
    "// Generated by scripts/embed-pdf-assets.py. Do not edit by hand.\n"
    f'window.SECRETT_PDF_ASSETS = {{font:"{font}",logo:"{logo}"}};\n',
    encoding="ascii",
)
