"""Bundle the public PDF font and logo for browsers that block runtime fetches."""

import base64
from pathlib import Path

root = Path(__file__).resolve().parents[1]
assets = root / "assets"
font = base64.b64encode((assets / "NotoSans-Regular.ttf").read_bytes()).decode("ascii")
logo = base64.b64encode((assets / "aisha-logo.png").read_bytes()).decode("ascii")
(assets / "pdf-assets.js").write_text(
    "// Generated by scripts/embed-pdf-assets.py. Do not edit by hand.\n"
    f'window.AISHA_PDF_ASSETS = {{font:"{font}",logo:"{logo}"}};\n',
    encoding="ascii",
)
